import type { Category, Product } from "./types"

export const categories: Category[] = [
  {
    id: "cocina",
    name: "Cocina",
    slug: "cocina",
    subcategories: [
      { id: "heladeras", name: "Heladeras" },
      { id: "lavarropas", name: "Lavarropas" },
      { id: "cocinas", name: "Cocinas y Anafes" },
      { id: "microondas", name: "Microondas" },
      { id: "freezers", name: "Freezers" },
      { id: "lavavajillas", name: "Lavavajillas" },
      { id: "campanas", name: "Campanas" },
    ],
  },
  {
    id: "limpieza",
    name: "Limpieza",
    slug: "limpieza",
    subcategories: [
      { id: "aspiradoras", name: "Aspiradoras" },
      { id: "lavadoras-tapizados", name: "Lavadoras de tapizados" },
      { id: "vapor", name: "Limpiadoras a vapor" },
      { id: "robots", name: "Robots aspiradora" },
      { id: "enceradoras", name: "Enceradoras" },
      { id: "hidrolavadoras", name: "Hidrolavadoras" },
      { id: "limpieza-industrial", name: "Limpieza industrial" },
    ],
  },
  {
    id: "climatizacion",
    name: "Climatización",
    slug: "climatizacion",
    subcategories: [
      { id: "aires", name: "Aires acondicionados" },
      { id: "ventiladores", name: "Ventiladores" },
      { id: "calefactores", name: "Calefactores" },
      { id: "estufas", name: "Estufas" },
      { id: "purificadores", name: "Purificadores" },
      { id: "deshumidificadores", name: "Deshumidificadores" },
      { id: "humidificadores", name: "Humidificadores" },
    ],
  },
  {
    id: "termos",
    name: "Termos & Mate",
    slug: "termos",
    subcategories: [
      { id: "termos", name: "Termos" },
      { id: "mates", name: "Mates" },
      { id: "bombillas", name: "Bombillas" },
      { id: "sets-materos", name: "Sets materos" },
      { id: "yerberas", name: "Yerberas" },
      { id: "materas", name: "Materas" },
      { id: "vasos-termicos", name: "Vasos térmicos" },
    ],
  },
  {
    id: "pequenos",
    name: "Pequeños electros",
    slug: "pequenos",
    subcategories: [
      { id: "licuadoras", name: "Licuadoras" },
      { id: "cafeteras", name: "Cafeteras" },
      { id: "tostadoras", name: "Tostadoras" },
      { id: "pavas", name: "Pavas eléctricas" },
      { id: "freidoras", name: "Freidoras de aire" },
      { id: "batidoras", name: "Batidoras" },
      { id: "procesadoras", name: "Procesadoras" },
      { id: "sandwicheras", name: "Sandwicheras" },
    ],
  },
  {
    id: "tv-audio",
    name: "TV & Audio",
    slug: "tv-audio",
    subcategories: [
      { id: "smart-tv", name: "Smart TV" },
      { id: "parlantes", name: "Parlantes" },
      { id: "soundbars", name: "Soundbars" },
      { id: "auriculares", name: "Auriculares" },
      { id: "proyectores", name: "Proyectores" },
      { id: "streaming", name: "Streaming" },
      { id: "microfonos", name: "Micrófonos" },
    ],
  },
  {
    id: "tecnologia",
    name: "Tecnología",
    slug: "tecnologia",
    subcategories: [
      { id: "celulares", name: "Celulares" },
      { id: "tablets", name: "Tablets" },
      { id: "notebooks", name: "Notebooks" },
      { id: "smartwatch", name: "Smartwatch" },
      { id: "gaming", name: "Gaming" },
      { id: "perifericos", name: "Periféricos" },
      { id: "almacenamiento", name: "Almacenamiento" },
    ],
  },
  {
    id: "cuidado-personal",
    name: "Cuidado personal",
    slug: "cuidado-personal",
    subcategories: [
      { id: "secadores", name: "Secadores" },
      { id: "planchitas", name: "Planchitas" },
      { id: "afeitadoras", name: "Afeitadoras" },
      { id: "depiladoras", name: "Depiladoras" },
      { id: "balanzas", name: "Balanzas" },
      { id: "masajeadores", name: "Masajeadores" },
      { id: "cepillos", name: "Cepillos faciales" },
    ],
  },
  {
    id: "herramientas",
    name: "Herramientas",
    slug: "herramientas",
    subcategories: [
      { id: "taladros", name: "Taladros" },
      { id: "atornilladores", name: "Atornilladores" },
      { id: "sierras", name: "Sierras" },
      { id: "soldadoras", name: "Soldadoras" },
      { id: "compresores", name: "Compresores" },
      { id: "kits", name: "Kits de herramientas" },
      { id: "medicion", name: "Medición" },
    ],
  },
  {
    id: "outdoor",
    name: "Outdoor",
    slug: "outdoor",
    subcategories: [
      { id: "conservadoras", name: "Conservadoras" },
      { id: "camping", name: "Camping" },
      { id: "parrillas", name: "Parrillas" },
      { id: "linternas", name: "Linternas" },
      { id: "sillas", name: "Sillas plegables" },
      { id: "vasos", name: "Botellas térmicas" },
      { id: "coolers", name: "Coolers" },
    ],
  },
  {
    id: "dormitorio",
    name: "Dormitorio",
    slug: "dormitorio",
    subcategories: [
      { id: "colchones", name: "Colchones" },
      { id: "sommiers", name: "Sommiers" },
      { id: "almohadas", name: "Almohadas" },
      { id: "ropa-cama", name: "Ropa de cama" },
      { id: "mesas-luz", name: "Mesas de luz" },
      { id: "placares", name: "Placares" },
      { id: "respaldo", name: "Respaldos" },
    ],
  },
  {
    id: "oficina",
    name: "Oficina",
    slug: "oficina",
    subcategories: [
      { id: "sillas-escritorio", name: "Sillas de escritorio" },
      { id: "escritorios", name: "Escritorios" },
      { id: "impresoras", name: "Impresoras" },
      { id: "monitores", name: "Monitores" },
      { id: "routers", name: "Routers" },
      { id: "ups", name: "UPS" },
      { id: "accesorios", name: "Accesorios" },
    ],
  },
]

export const products: Product[] = [
  {
    id: "p-001",
    slug: "limpiador-alfombras-tapizados-portatil",
    name: "Limpiador de Alfombras y Tapizados Portátil",
    description: "2 en 1 con cepillo de limpieza, 600W de succión 17KPA, ligero y compacto.",
    retailPrice: 180000,
    wholesalePrice: 150000,
    imageUrl: "/placeholder.svg",
    categoryId: "limpieza",
    subcategoryId: "lavadoras-tapizados",
    brand: "TermoLine",
    stock: 24,
    highlights: ["2 EN 1 cepillo de limpieza", "600W · Succión 17KPA", "3.5KG ligero y compacto", "Tanque de agua 1.1L"],
    promotion: { tipo: "porcentaje", valor: 10, activa: true },
  },
  {
    id: "p-002",
    slug: "heladera-bgh-inverter-405l",
    name: "Heladera BGH Inverter 405L",
    description: "Heladera con freezer superior, 405L de capacidad, eficiencia A++.",
    retailPrice: 920000,
    wholesalePrice: 760500,
    imageUrl: "/placeholder.svg",
    categoryId: "cocina",
    subcategoryId: "heladeras",
    brand: "BGH",
    stock: 8,
    highlights: ["405L de capacidad", "310L compartimiento refrigerador", "94L compartimiento congelador", "Eficiencia energética A++"],
  },
  {
    id: "p-003",
    slug: "termo-stanley-classic-1l",
    name: "Termo Stanley Classic 1L",
    description: "Termo de acero inoxidable con conservación térmica de 24hs.",
    retailPrice: 95000,
    wholesalePrice: 78000,
    imageUrl: "/placeholder.svg",
    categoryId: "termos",
    subcategoryId: "termos",
    brand: "Stanley",
    stock: 60,
    highlights: ["1L capacidad", "24hs frío/calor", "Acero inoxidable 18/8"],
    promotion: { tipo: "nxm", valor: 3, valor_secundario: 2, activa: true },
  },
  {
    id: "p-004",
    slug: "aire-split-3500-frigorias-inverter",
    name: "Aire Split 3500 Frigorías Inverter",
    description: "Aire acondicionado split frío/calor, tecnología inverter, control wifi.",
    retailPrice: 720000,
    wholesalePrice: 615000,
    imageUrl: "/placeholder.svg",
    categoryId: "climatizacion",
    subcategoryId: "aires",
    brand: "Surrey",
    stock: 12,
    highlights: ["3500 frigorías", "Inverter", "Wifi · App control"],
  },
  {
    id: "p-005",
    slug: "lavarropas-drean-8kg",
    name: "Lavarropas Drean Next 8.12 Eco",
    description: "Carga frontal de 8KG, 1200 RPM, programa rápido 30 minutos.",
    retailPrice: 685000,
    wholesalePrice: 580000,
    imageUrl: "/placeholder.svg",
    categoryId: "cocina",
    subcategoryId: "lavarropas",
    brand: "Drean",
    stock: 6,
    highlights: ["8KG carga", "1200 RPM", "12 programas"],
    promotion: { tipo: "fijo", valor: 50000, activa: true },
  },
  {
    id: "p-006",
    slug: "microondas-atma-easy-23l",
    name: "Microondas Atma Easy 23L",
    description: "Microondas digital de 23 litros con grill y panel táctil.",
    retailPrice: 165000,
    wholesalePrice: 138000,
    imageUrl: "/placeholder.svg",
    categoryId: "cocina",
    subcategoryId: "microondas",
    brand: "Atma",
    stock: 30,
    highlights: ["23L capacidad", "Grill", "Panel digital"],
  },
  {
    id: "p-007",
    slug: "cafetera-express-philco-15bar",
    name: "Cafetera Express Philco 15 Bar",
    description: "Cafetera con vaporizador, depósito 1.5L y bomba italiana de 15 bares.",
    retailPrice: 245000,
    wholesalePrice: 210000,
    imageUrl: "/placeholder.svg",
    categoryId: "pequenos",
    subcategoryId: "cafeteras",
    brand: "Philco",
    stock: 18,
    highlights: ["15 bares de presión", "Vaporizador", "Depósito 1.5L"],
    promotion: { tipo: "porcentaje", valor: 15, activa: true },
  },
  {
    id: "p-008",
    slug: "ventilador-pie-liliana-20",
    name: 'Ventilador de Pie Liliana 20"',
    description: "Ventilador de pie 20 pulgadas, 3 velocidades y oscilación.",
    retailPrice: 88000,
    wholesalePrice: 72000,
    imageUrl: "/placeholder.svg",
    categoryId: "climatizacion",
    subcategoryId: "ventiladores",
    brand: "Liliana",
    stock: 45,
    highlights: ["20 pulgadas", "3 velocidades", "Oscilación 90°"],
  },
  {
    id: "p-009",
    slug: "aspiradora-philips-fc-1500w",
    name: "Aspiradora Philips PowerGo 1500W",
    description: "Aspiradora con filtro EPA y bolsa reutilizable, mango plegable.",
    retailPrice: 195000,
    wholesalePrice: 165000,
    imageUrl: "/placeholder.svg",
    categoryId: "limpieza",
    subcategoryId: "aspiradoras",
    brand: "Philips",
    stock: 22,
    highlights: ["1500W", "Filtro EPA", "Bolsa reutilizable"],
  },
  {
    id: "p-010",
    slug: "mate-imperial-acero",
    name: "Mate Imperial de Acero",
    description: "Mate de acero inoxidable con base antideslizante, fácil limpieza.",
    retailPrice: 28000,
    wholesalePrice: 22000,
    imageUrl: "/placeholder.svg",
    categoryId: "termos",
    subcategoryId: "mates",
    brand: "TermoLine",
    stock: 120,
    highlights: ["Acero 304", "Base antideslizante", "Fácil limpieza"],
    promotion: { tipo: "nxm", valor: 2, valor_secundario: 1, activa: true },
  },
  {
    id: "p-011",
    slug: "tostadora-atma-2-rebanadas",
    name: "Tostadora Atma TO-9020 2 Rebanadas",
    description: "Tostadora con bandeja recogemigas, 6 niveles de tostado.",
    retailPrice: 62000,
    wholesalePrice: 51000,
    imageUrl: "/placeholder.svg",
    categoryId: "pequenos",
    subcategoryId: "tostadoras",
    brand: "Atma",
    stock: 40,
    highlights: ["2 rebanadas", "6 niveles", "Bandeja recogemigas"],
  },
  {
    id: "p-012",
    slug: "calefactor-tiro-balanceado-3000",
    name: "Calefactor Tiro Balanceado 3000kcal",
    description: "Calefactor a gas natural, ideal para ambientes de hasta 35m².",
    retailPrice: 280000,
    wholesalePrice: 235000,
    imageUrl: "/placeholder.svg",
    categoryId: "climatizacion",
    subcategoryId: "calefactores",
    brand: "Eskabe",
    stock: 14,
    highlights: ["3000 kcal", "Tiro balanceado", "Gas natural"],
  },
]

export function getCategoryById(id: string) {
  return categories.find((c) => c.id === id)
}

export function getSubcategoryName(categoryId: string, subcategoryId: string) {
  const category = getCategoryById(categoryId)
  return category?.subcategories.find((s) => s.id === subcategoryId)?.name ?? subcategoryId
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug)
}

export function getProductById(id: string) {
  return products.find((p) => p.id === id)
}
